# Generated by Django 5.0.6 on 2024-07-03 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre del nutriente')),
                ('type_of_nutrient', models.CharField(max_length=45, verbose_name='Tipo de nutriente')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción del nutriente')),
                ('levels', models.CharField(choices=[('BAJO', 'Bajo'), ('OPTIMO', 'Optimo'), ('ELEVADO', 'Elevado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('levels', models.CharField(choices=[('BAJO', 'Bajo'), ('OPTIMO', 'Optimo'), ('ELEVADO', 'Elevado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=100)),
                ('parameters', models.FloatField()),
                ('nutrients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrientes.nutrientes')),
                ('ph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrientes.ph')),
                ('type_of_terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrientes.tipoterreno')),
            ],
        ),
    ]
