# Generated by Django 5.0.6 on 2024-07-18 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herramientas_agricultura_precision', '0001_initial'),
        ('suelo', '0001_initial'),
        ('tipo_siembra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariedadMango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=500)),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suelo.tiposuelo')),
                ('sowing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_siembra.tiposiembra')),
                ('type_of_market', models.ManyToManyField(to='herramientas_agricultura_precision.tipomercado')),
            ],
            options={
                'verbose_name_plural': 'Variedades de mango',
                'db_table': 'Variedad_mango',
            },
        ),
    ]
