# Generated by Django 5.0.6 on 2024-07-03 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hectareas', '0001_initial'),
        ('herramientas_agricultura_precision', '0001_initial'),
        ('nutrientes', '0001_initial'),
        ('tipo_siembra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('alert', models.BooleanField(default=True, verbose_name='Alerta')),
                ('message', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=100)),
                ('PH', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrientes.ph')),
                ('nutrients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrientes.nutrientes')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrientes.tiposuelo')),
            ],
        ),
        migrations.CreateModel(
            name='VariedadMango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=100)),
                ('hectareas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hectareas.hectareas')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrientes.tiposuelo')),
                ('sowing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_siembra.tiposiembra')),
                ('type_of_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herramientas_agricultura_precision.tipomercado')),
            ],
        ),
    ]
