# Generated by Django 5.0.6 on 2024-07-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas_agricultura_precision', '0001_initial'),
        ('variedad_mango', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisissuelo',
            name='soil_fertility',
        ),
        migrations.RemoveField(
            model_name='variedadmango',
            name='hectareas',
        ),
        migrations.RemoveField(
            model_name='variedadmango',
            name='type_of_market',
        ),
        migrations.AddField(
            model_name='variedadmango',
            name='type_of_market',
            field=models.ManyToManyField(to='herramientas_agricultura_precision.tipomercado'),
        ),
    ]
