# Generated by Django 5.0.6 on 2024-07-02 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HerAgri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=145, verbose_name='Nombre de la herramienta')),
                ('description', models.TextField(max_length=100, verbose_name='Descripción de la herramienta')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre del tipo de mercado')),
                ('description', models.TextField(max_length=100, verbose_name='Descripción del tipo de mercado')),
                ('her_agri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herramientas_agricultura_precision.heragri')),
            ],
        ),
    ]
