# Generated by Django 5.0.6 on 2024-07-05 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrenajeSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('MALO', 'Malo'), ('BUENO', 'Bueno'), ('ADECUADO', 'Adecuado')], max_length=50, verbose_name='Nivel de drenaje')),
                ('value', models.FloatField(verbose_name='Valor de referencia')),
                ('infiltration_rate', models.FloatField(verbose_name='Tasa de infiltración')),
                ('field_capacity', models.FloatField(verbose_name='Capacidad de campo')),
                ('wilting_point', models.FloatField(verbose_name='Punto de marchitez')),
                ('permeability', models.FloatField(verbose_name='Permiabilidad')),
                ('porosity', models.FloatField(verbose_name='Porosidad')),
            ],
            options={
                'verbose_name_plural': 'Drenajes del suelo',
                'db_table': 'Drenaje_suelo',
            },
        ),
        migrations.CreateModel(
            name='FertilidadSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre del nutriente')),
                ('type_of_nutrient', models.CharField(max_length=45, verbose_name='Tipo de nutriente')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción del nutriente')),
                ('level', models.CharField(choices=[('MUY BAJO', 'Muy Bajo'), ('BAJO', 'Bajo'), ('MODERADO', 'Moderado'), ('ALTO', 'Alto')], max_length=20, verbose_name='Nivel del nutriente')),
                ('value', models.FloatField(verbose_name='Valor del nutriente')),
            ],
            options={
                'verbose_name_plural': 'FertilidadSuelo',
                'db_table': 'Fertilidad_suelo',
            },
        ),
        migrations.CreateModel(
            name='pH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('level', models.CharField(choices=[('BAJO', 'Bajo'), ('OPTIMO', 'Optimo'), ('ELEVADO', 'Elevado')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'pH',
                'db_table': 'ph',
            },
        ),
        migrations.CreateModel(
            name='TexturaSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Arena', 'Arena'), ('Limo', 'Limo'), ('Arcilla', 'Arcilla')], max_length=20, verbose_name='Nombre de textura')),
                ('value', models.FloatField()),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Texturas del suelo',
                'db_table': 'Textura_Suelo',
            },
        ),
        migrations.CreateModel(
            name='TipoTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Tipos de terrenos',
                'db_table': 'Tipo_terreno',
            },
        ),
        migrations.CreateModel(
            name='TipoSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=500)),
                ('nutrients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suelo.fertilidadsuelo')),
                ('ph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suelo.ph')),
                ('type_of_terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suelo.tipoterreno')),
            ],
            options={
                'verbose_name_plural': 'Tipos de suelos',
                'db_table': 'tipo_suelo',
            },
        ),
    ]
