# Generated by Django 5.0.6 on 2024-07-05 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FertilidadSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre del nutriente')),
                ('type_of_nutrient', models.CharField(max_length=45, verbose_name='Tipo de nutriente')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción del nutriente')),
                ('level', models.CharField(choices=[('MUY BAJO', 'Muy Bajo'), ('BAJO', 'Bajo'), ('MODERADO', 'Moderado'), ('ALTO', 'Alto')], max_length=20)),
                ('value', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'FertilidadSuelo',
            },
        ),
        migrations.CreateModel(
            name='pH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('level', models.CharField(choices=[('BAJO', 'Bajo'), ('OPTIMO', 'Optimo'), ('ELEVADO', 'Elevado')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'pH',
            },
        ),
        migrations.CreateModel(
            name='TipoTerreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Tipos de terrenos',
            },
        ),
        migrations.CreateModel(
            name='TipoSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=500)),
                ('nutrients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suelo.fertilidadsuelo')),
                ('ph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suelo.ph')),
                ('type_of_terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suelo.tipoterreno')),
            ],
            options={
                'verbose_name_plural': 'Tipos de suelos',
            },
        ),
    ]
