# Generated by Django 5.0.6 on 2024-07-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suelo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilidadsuelo',
            name='level',
        ),
    ]
