# Generated by Django 5.0.6 on 2024-07-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suelo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ph',
            name='value',
        ),
        migrations.AddField(
            model_name='ph',
            name='max_value',
            field=models.FloatField(default=7.0, verbose_name='Valor máximo del pH'),
        ),
        migrations.AddField(
            model_name='ph',
            name='min_value',
            field=models.FloatField(default=5.5, verbose_name='Valor mínimo del pH'),
        ),
    ]
