# Generated by Django 5.0.6 on 2024-07-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suelo', '0002_remove_fertilidadsuelo_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drenajesuelo',
            name='level',
        ),
        migrations.RemoveField(
            model_name='ph',
            name='level',
        ),
        migrations.AddField(
            model_name='ph',
            name='value',
            field=models.FloatField(default=7.0, verbose_name='Valor del pH'),
        ),
    ]
