# Generated by Django 5.0.6 on 2024-07-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suelo', '0003_remove_drenajesuelo_level_remove_ph_level_ph_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilidadsuelo',
            name='type_of_nutrient',
        ),
        migrations.AddField(
            model_name='fertilidadsuelo',
            name='level',
            field=models.CharField(choices=[('BAJO', 'Bajo'), ('OPTIMO', 'Optimo'), ('ELEVADO', 'Elevado')], default='OPTIMO', max_length=255, verbose_name='Nivel del nutiente'),
        ),
        migrations.AddField(
            model_name='ph',
            name='level',
            field=models.CharField(choices=[('BAJO', 'Bajo'), ('OPTIMO', 'Optimo'), ('ELEVADO', 'Elevado')], default='OPTIMO', max_length=255, verbose_name='Nivel del nutiente'),
        ),
        migrations.AlterField(
            model_name='texturasuelo',
            name='name',
            field=models.CharField(choices=[('Arena', 'Arena'), ('Limo', 'Limo'), ('Arcilla', 'Arcilla')], default='', max_length=20, verbose_name='Nombre de textura'),
        ),
        migrations.RemoveField(
            model_name='tiposuelo',
            name='nutrients',
        ),
        migrations.AddField(
            model_name='tiposuelo',
            name='nutrients',
            field=models.ManyToManyField(to='suelo.fertilidadsuelo'),
        ),
    ]
