# Generated by Django 5.0.6 on 2024-07-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hectareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.FloatField()),
                ('description', models.TextField(max_length=100, verbose_name='Descripción')),
            ],
        ),
    ]
