# Generated by Django 5.0.6 on 2024-07-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hectareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hectareas',
            name='number_trees',
            field=models.IntegerField(default=0, editable=False, verbose_name='Cantidad de Árboles'),
        ),
    ]
