# Generated by Django 5.0.6 on 2024-07-18 14:19

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suelo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisSuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Análisis del suelo', editable=False, max_length=20)),
                ('infiltration_rate', models.FloatField()),
                ('field_capacity', models.FloatField()),
                ('point_wither', models.FloatField()),
                ('permeability', models.FloatField()),
                ('porosity', models.FloatField()),
                ('alert', models.BooleanField(default=False, verbose_name='Alerta')),
                ('message', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('ph', models.FloatField()),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('calcium', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('sulfur', models.FloatField()),
                ('iron', models.FloatField()),
                ('manganese', models.FloatField()),
                ('zinc', models.FloatField()),
                ('copper', models.FloatField()),
                ('molybdenum', models.FloatField()),
                ('boron', models.FloatField()),
                ('soil_texture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suelo.texturasuelo')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suelo.tiposuelo')),
                ('usuario', models.ForeignKey(default=users.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Analisis del suelo',
                'db_table': 'analisis_de_suelo',
            },
        ),
    ]
