# Generated by Django 5.0.6 on 2024-07-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSiembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Tipo de siembra')),
                ('description', models.TextField(max_length=1000, verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Tipos de siembra',
            },
        ),
    ]
