# Generated by Django 5.0.6 on 2024-07-05 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variedad_mango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisFoliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Suficiente', 'Suficiente'), ('Alto', 'Alto'), ('Exceso', 'Exceso')], max_length=10)),
                ('nutrient', models.CharField(max_length=45)),
                ('soil_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variedad_mango.analisissuelo')),
            ],
            options={
                'verbose_name_plural': 'Análisis Florial',
                'db_table': 'Analisis_Foliar',
            },
        ),
    ]
