# Generated by Django 5.0.6 on 2024-07-16 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analisis_suelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisFoliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient', models.CharField(max_length=45)),
                ('level', models.CharField(choices=[('BAJO', 'Bajo'), ('OPTIMO', 'Óptimo'), ('ELEVADO', 'Elevado')], default=0, max_length=10, verbose_name='Nivel')),
                ('soil_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis_suelo.analisissuelo')),
            ],
            options={
                'verbose_name_plural': 'Análisis Foliar',
                'db_table': 'Analisis_Foliar',
            },
        ),
    ]
