# Generated by Django 5.0.6 on 2024-07-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_foliar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisisfoliar',
            options={'verbose_name_plural': 'Análisis Foliar'},
        ),
    ]
