# Generated by Django 5.0.6 on 2024-07-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis_foliar', '0003_remove_analisisfoliar_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisisfoliar',
            name='level',
            field=models.CharField(choices=[('BAJO', 'Bajo'), ('OPTIMO', 'Óptimo'), ('ELEVADO', 'Elevado')], default=0, max_length=10, verbose_name='Nivel'),
        ),
    ]
