# Generated by Django 5.0.6 on 2024-07-02 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herramientas_agricultura_precision', '0001_initial'),
        ('variedad_mango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('her_agri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herramientas_agricultura_precision.heragri')),
                ('mango_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variedad_mango.variedadmango')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variedad_mango.aptitudsuelo')),
            ],
        ),
    ]
