# Generated by Django 5.0.6 on 2024-07-18 14:19

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analisis_suelo', '0001_initial'),
        ('herramientas_agricultura_precision', '0001_initial'),
        ('tipo_siembra', '0001_initial'),
        ('variedad_mango', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=1000)),
                ('start_date', models.DateField()),
                ('harvest_date', models.DateField()),
                ('hectareas', models.FloatField(default=2)),
                ('mango_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variedad_mango.variedadmango')),
                ('sowing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_siembra.tiposiembra')),
                ('state', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='analisis_suelo.analisissuelo')),
                ('tools', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herramientas_agricultura_precision.herramientas')),
                ('type_of_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herramientas_agricultura_precision.tipomercado')),
                ('usuario', models.ForeignKey(default=users.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cultivos',
                'db_table': 'Cultivos',
            },
        ),
    ]
